version: '3.4'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    ports:
      - "8000:8000"
      - "9090:9090"
    command: ["pm2-runtime", "server.js"]
